### ISSUE TITLE
¿Existe algo similar ya creado para telemetría?

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#1]

**Comment by Sediug** [comment]
https://github.com/BallAerospace/COSMOS

**Comment by Sediug** [comment]
Cuando tenga tiempo sigo mirando pero al final molaría traer los datos a una web y mostrarlo con sockets en tiempo real. :100:

**Comment by UlisesGascon** [comment]
Se puede hacer facil con Firebase (gestión total de trafico y demás) o WebSocket nuestro con Node y pillars... tengo cosas ya montadas :-)

Creo que la idea es hacer algo como 
1. COmunicación del coche a una Raspi
2. Comunicación de la Raspi a Internet via 4G o Wifi...
3. Difusión y expasión por web usando Cloud con solución propia o Firebase... Serverless

**Comment by Sediug** [comment]
Mola. Firebase mola porque se implementa super rapido y sencillo. Yo también he montado algo con Node, sockets y pillars, asique lo que estimemos mejor, las dos son viables :+1:  .

¿La wifi iría bien en un circuito de carreras? Quiza habría que implementar un sistema via 4G.

**Comment by CodingCarlos** [comment]
Yo no confío en que la red wifi vaya a funcionar, y directamente plantearía una solución 4g.

En el peor de los casos, se puede buscar un android barato y viejo con una tarjeta prepago, y usarlo como router wifi para la Raspberry

**Comment by Sediug** [comment]
Si me da que va a ser lo mejor. Además para mandar cuatro datos con una tarifa pequeña sobra.

**Comment by UlisesGascon** [comment]
Por cierto... Hablando con Kr0n0 me propuso esto, para sistemas en tiempo real con determinismo y priorización.

**Arduino y FreeRTOS**
https://www.freertos.org/
https://feilipu.me/2015/11/24/arduino_freertos/
https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/index.html
https://github.com/greiman/FreeRTOS-Arduino

¿Qué os parece @CodingCarlos @Sediug ?

**Comment by UlisesGascon** [comment]
Sistema final decidido e issue cerrado...
