### ISSUE TITLE
Pack de patrocinios e información

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#11]
Hola!

Me estoy moviendo con posibles patrocinadores...

¿Teneis algo de info organizada para ofrecerles en plan... tipos de patrocinio, que entra y que no.. etc..?

**Comment by dagomezl** [comment]
Nuestro dossier:
[FUC3M_2018_Dossier_v3.0__1__20180303094934.pdf](https://github.com/OSWeekends/formula-uc3m/files/1785644/FUC3M_2018_Dossier_v3.0__1__20180303094934.pdf)

**Comment by UlisesGascon** [comment]
Cerrado el issue y añadido a #17
