### ISSUE TITLE
Lo que tebnemos en el coche

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#12]
**hw**
- Arduino Mega

**Sensores existentes**
-  4 amortiguadores.
- 4 presión de freno
- 4 temperatura de freno
- 4 termistores en el radiador
- 1 sobre el tubo de pitot (presion de aire y demás...)
- 4 efecto HAL de las ruedas (Velocidad de cada rueda)
- 4 de presión de neumáticos a 433MHz
- GPS

**Sensores deseados**
- 2 posicion de pedales (NO EXISTE/PENSAMIENTO)
- 1 posición dirección (No existe)
- 1 efecto HAL (mide ??) (No existe)
- 2 termopares en la mangueta (donde se sujeta la pinza de freno) (No existe)
- ECU (Caja negra por ver que pasa dentro: CAN-BUS)

### Preguntas:

- ¿Tiempos de respuesta esperados por sensor? pj.... 100ms, 1000ms, etc...
- ¿Qué datos da cada sensor?
- ¿Qué modelos de sensores tenemos, para sacar datasheets?

**Comment by rubenmoreno94** [comment]
**¿Tiempos de respuesta esperados por sensor? pj.... 100ms, 1000ms, etc...**
El caso más exigente es el de los sensores de los amortiguadores. Actualmente hemos conseguido obtener datos cada 30 ms aprox. Lo óptimo sería recibirlos cada 20 ms y en su defecto en menos de 100 ms, cuanto más bajo mejor

**Modelos de los sensores para sacar datasheets**
Entre esta noche y mañana recopilo todos los datasheets. Tengo para dejaros un termistor como el de los radiadores,

**Comment by rubenmoreno94** [comment]
**Modelos de los sensores para sacar datasheets**
[Datasheets.zip](https://github.com/OSWeekends/formula-uc3m/files/1830425/Datasheets.zip)

Los sensores de amortiguadores dan un valor entre 0 y 1023 así que se pueden sustituir por un potenciómetro

Los sensores de posición de pedales y de la dirección van a ser potenciómetros.
Y el de efecto hall que no es el de las ruedas es un sensor que viene en el motor de serie y mide la velocidad. Creo que da una diferencia de voltaje y con eso se calcula la velocidad (pendiente de confirmar)

**Comment by UlisesGascon** [comment]
Migrado a _Datos Finales del coche #45_
