### ISSUE TITLE
Decisiones y acciones para el Sprint 0

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#13]
### Pendiente
- [X] readme.md (@bytelovers y @rubenmoreno94)
- [ ] Backlog.md (@Ulises y @rubenmoreno94)
- [X] Ver que tenemos a todo el mundo en Github
- [X] Reuniones semanales, los viernes en Spotahome. Gracias @mceire!
 
### Decisiones
- [ ] El coche gestiona las transaciones HTTP
- [ ] Sprints de dos semanas y reparto máximo de tareas
- [X] Conexión a internet por 4G directamente
- [ ] Conexion con los sensores por comunicacion serial usando Arduino Mega
- [ ] Hacer un equipo funcional en Campus para organizar el desarrollo
- [ ] Dividir el desarrollo en TEAM ArduData (del coche a firebase) y TEAM DataVisual (de firebase a cliente)
- [ ] BUS i2c para comunicarnos con el arduino(s) - Raspi

### Equipos
- Formula 
- TEAM ArduData (del coche a API (Back)) liderado por @bifuer con @Sediug  👍 
- TEAM DataVisual (de API (Back) a cliente) liderado por @CodingCarlos con @jonasync

### Investigar
- Comunicacion con http o mqtt?
- calibracion con @bifuer :trollface: 

### Backlog negocio
- Sacar datos en tiempo real 
- Visualizarlos en tiempo real (via web) de los datos críticos 
- Poder recopilar los datos COMPLETOS y verlos para análisis

### Arquitectura
**Coche**
- Arduino a pelo

**back**
- Goku para hosting
- Mongodb: Base de datos
- Mosca: broker mqtt para nodejs, da websockets para front

**front**
- Vue: porque Baumann...
- D3: para mostrar data...

### Draft de releases
- 30 Marzo. Fin P0 + Materiales comprados
- 15 Abril. Fin P1 MVP del sistema (1 sensor o varios)
- Varias iteraciones más....
- 10 JUNIO Release de la version 1.0. Desde ese monteto solución de bugs y recolecion de feedback
- 31 Julio competición

**Comment by bytelovers** [comment]
Podemos echarle un ojo a este post que hay una pequeña aproximación de lo que queremos montar

https://remote-lab.net/raspberry-pi-car-automation

**Comment by UlisesGascon** [comment]
_Ya tenemos mas actualizaciones y esto quedo obsoleto_
