### ISSUE TITLE
Crear un readme.md del equipo

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#14]
### Pendiente
- [x] Crear un readme.md partiendo de la plantilla de los Guilds
- [x] Actualizar el readme.md

**Comment by UlisesGascon** [comment]
Amig@s de la uni... nos faltan vuestors nicks y nombres... podeis actualizarlo en el readme? **Gracias**

**Comment by rubenmoreno94** [comment]
Hecho!!!
