### ISSUE TITLE
Comprar materiales para "replicar" el coche en Campus

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#18]
### Pendiente
- [x] Debatir la lista de los reyes magos
- [x] Conseguir los materiales de la comundiad o improvisar/comprar las cosas por Amazon/Ebay (@ulisesGascon)

**Comment by bifuer** [comment]
Yo? De que se trata, buscar los componentes y montar un prototipo sin el coche para emular inputs con pots y tal?

**Comment by jonasync** [comment]
**Team campus**
- 2x Raspi 3
- 2x Arduino Mega
- 1x Shield 4g para Raspi

**Team coche**
- Raspi 3
- 1x Shield 4g para Raspi

**Comment by jonasync** [comment]
### Propuestas descartadas:
- https://www.amazon.es/Altitud-Tech-velocidad-inal%C3%A1mbrico-amplificador/dp/B0749RNJ18/ref=sr_1_4?ie=UTF8&qid=1521835980&sr=8-4&keywords=raspberry+4g
- https://www.amazon.es/Altitud-Tech-pi014-hardware-ordenadores-Raspberry/dp/B0749RPKV8/ref=sr_1_2?ie=UTF8&qid=1521835980&sr=8-2&keywords=raspberry+4g
- http://ecommerce.linkwave.co.uk/pilot/
- https://www.cooking-hacks.com/shop/wireless/gprs-3g-4g

**Comment by UlisesGascon** [comment]
Tengo materiales ya en campus! Para el domingo los bajo ^^. Podemos dejarlos en campus para cuando los necesitemos
