### ISSUE TITLE
Reglas competición

### ISSUE THREAD

**Issue by Sediug** [OSWeekends/formula-uc3m#2]
Habría que buscar un reglamento de la competición y leerlo bien para saber cuales son nuestras limitaciones a la hora de pensar el sistema.

**Comment by dagomezl** [comment]
Estas son las reglas que valen en las competiciones que asistimos 
https://www.formulastudent.de/uploads/media/FS-Rules_2018_V1.1.pdf

**Comment by UlisesGascon** [comment]
Cerrado el issue y añadido a #17
