### ISSUE TITLE
Reunión de equipo: Viernes 23 Marzo

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#21]
### ¿Quien se apunta?

Viernes 23 Marzo a las 20:00 en [Spotahome (Calle de Vizcaya, 12. Madrid)](https://www.google.com/maps?cid=1189299906260060111)

![](https://media.giphy.com/media/10hO3rDNqqg2Xe/giphy.gif)

**Comment by bytelovers** [comment]
tiene toda la pinta de hacer hangouts....

**Comment by jonasync** [comment]
Yo me acercaré si no hay cambios

**Comment by rubenmoreno94** [comment]
Yo tambien voy
