### ISSUE TITLE
¿Quien son los competidores?

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#3]
### Dudas
- [ ] ¿Existe un listado?
- [ ] ¿Que coches tienen?
- [ ] ¿Algun equipo gana de forma regular?

**Comment by dagomezl** [comment]
En listado mundial es este separado por combustión y electrico https://mazur-events.de/fs-world/

**Comment by UlisesGascon** [comment]
Cerrado el issue y añadido a #17
