### ISSUE TITLE
Especificaciones de nuestro coche

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#4]
### Sería necesario saber....

- [ ] Mecánica (fuerza G, velocidades, punta...)
- [ ] Electronica (Baterias, consumos, etc...)

**Comment by Sediug** [comment]
Como idea loca, estaría guay ponerle un GPS al coche y pintar un minidibujo de los circuitos para poder hacer un seguimiento en tiempo de real de por donde va. ¿Tienen algo así ya? ¿Cuan descabellado sería?

**Comment by UlisesGascon** [comment]
si si... voto por eso tambien!!

**Comment by CodingCarlos** [comment]
También habría que saber qué necesidades tienen, y que datos aportarían más valor para priorizar la representación de esos.

**Comment by dagomezl** [comment]
Tenemos gps pero aún no implementado
Vel punta 110 kmh
Vel media en competición 50 kmh
G máxima 2.5
Batería de moto de 12V, alternador de moto para cargarla en marcha. Los consumos no lo se seguro pero el electroventilador y cambiovde marchas consumen casi todo lo he generado

**Comment by UlisesGascon** [comment]
Cerrado el issue y añadido a #17
