### ISSUE TITLE
¿Realtime Video?

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#5]
Estaría genial poder seguir las carreras de otros sitios como Campus.

Podemos montar un dashboard que muestre 1 o varias cámaras del coche + telemetría 

¿Como emitimos del coche a internet y de internet al mundo? 

Se me ocurre hablar con los amigos del [Teltoo](http://www.teltoo.com/)

**Comment by CodingCarlos** [comment]
Teltoo puede funcionar en la parte de internet al mundo, puedo hablar con Sergio. 

Yo tiraría por webrtc para mandar del coche al server, al menos en primera iteración. En algún sitio tengo guardado un ejemplo de real time streaming.

Me da un poco de miedo que esto se coma una cantidad de tráfico tal que nos añada un delay a los datos, que creo que aportan más valor. Habría que testear intensivamente.

**Comment by Sediug** [comment]
Si, es probable. Yo implementaría primero el sistema de datos para la telemetría y ya después lo del video, si lo del video come mucho ancho de red lo podemos poner en otra red 4G prepago barata o algo por el estilo.
