### ISSUE TITLE
¿Que medimos con telemetria y que tiempos?

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/formula-uc3m#6]
### Necesidades?
- [ ] GPS. 100ms?
- [ ] Temperaturas varias ?
- [ ] Torsiones?

**Comment by dagomezl** [comment]
Gps, temperaturas y suspensión en principio

**Comment by CodingCarlos** [comment]
Yo creo que con ventanas de entre 100 y 300ms tendríamos buenas mediciones. 

Sería interesante buscar qué hacen apps de GPS (hay una para bicis con la que podríamos contactar, que seguramente podamos sentarnos con ellos para que nos cuenten cosas)

**Comment by dagomezl** [comment]
Hay datos como temperatura que ese rango está bien pero por ejemplo la
suspensión cuanto más bajo mejor.

Hicimos una prueba con una de esas apps metiendo un móvil en el coche y nos
dio bastante error comparado con el gps de la gopro, creemos que fue por lo
pequeño del circuito, 200 m

**Comment by UlisesGascon** [comment]
Cerrado el issue y añadido a #17
