### ISSUE TITLE
Conexiones OBDII (ECU) hacia Rasp pi

### ISSUE THREAD

**Issue by bytelovers** [OSWeekends/formula-uc3m#7]
¿Que planteamiento podríamos escoger a la hora de transmitir la info hacia la raspberry? Aún así hay que empollarse el protocolo del puerto.
- [ ] Conexión OBDII WIFI / BT: habría que mirar latencias
- [ ] Conexión OBDII cable

¿Tenéis algo ya investigado?

**Comment by rubenmoreno94** [comment]
Yo diría que mejor utilizar una conexión por cable por simplicidad y fiabilidad

**Comment by UlisesGascon** [comment]
https://github.com/sebi2k1/node-can

**Comment by bytelovers** [comment]
He visto esto, que igual nos puede ayudar a futuro.... https://github.com/antonmills/Node-OBDII

**Comment by jonasync** [comment]
@rubenmoreno94 facilitar un fichero con backup de la info de una carrera de la ECU...

**Comment by rubenmoreno94** [comment]
Como sabéis no hay que sacar toda esa información. Sólo habria que sacar las RPM's, la ECT, el TP y un dato de un sensor para la temperatura del aceite que se va a colocar dentro del motor y que lo sacará en el mismo fichero

**Comment by bytelovers** [comment]
@rubenmoreno94 ¿averiguaste a qué correspondían los tiempos del CSV?

**Comment by UlisesGascon** [comment]
Migrado al debate de Arquitectura en #46
